### ISSUE TITLE
Folder-Like REST Object Selector

### ISSUE THREAD

**Issue by rgauss** [EasyDynamics/oscal-react-library#305]
As a user of the OSCAL Editor in REST mode, I want to be able to navigate the available OSCAL root objects in a tree structure that is more analogous to a folder structure so that I can relate that view to what I see in my file-persistent source directory.

### Acceptance Criteria
- A toggleable pane or drawer is available that displays a tree view of
  - Catalogs
  - Profiles
  - Component Definitions
  - System Security Plans
- The title for each object is shown
- Clicking on an object in the pane navigates to that editor page, loads the object, and highlights the object in the selector
- Links to the base path of the web app should show a message indicating an object should be selected rather than assuming the current default of catalogs
  - When not in REST mode catalogs can continue to be the default
- In this iteration it is acceptable if the pane is a fixed width
- In this iteration it is acceptable if there is no polling/push refresh capability, should only refresh on saves

### Implementation Notes
- We'll have to give careful consideration for the screen real-estate here
  - The [Drawer component](https://mui.com/components/drawers/) might make a good candidate

<img width="1921" alt="Screen_Shot_2022-06-08_at_6_45_44_AM" src="https://user-images.githubusercontent.com/168671/172599509-c5c25318-2560-4688-a1a1-75bcb6b2f811.png">

### Tasks
- [x] EasyDynamics/oscal-editor-deployment#98
- [x] EasyDynamics/oscal-react-library#466
- [x] EasyDynamics/oscal-react-library#467
- [x] EasyDynamics/oscal-react-library#468
- [x] EasyDynamics/oscal-react-library#469
- [x] EasyDynamics/oscal-editor-deployment#115

**Comment by tuckerzp** [comment]
Looking into this a bit more https://mui.com/material-ui/react-drawer/#persistent-drawer seems like it would work really well.

**Comment by tuckerzp** [comment]
@rgauss or @kylelaker would we want to actually be an `OSCAL component`? The subtasks we created were originally assuming it would be a component but looking how we do the `Menu` currently, I am unsure.

**Comment by kylelaker** [comment]
> would we want to actually be an `OSCAL component`? The subtasks we created were originally assuming it would be a component but looking how we do the `Menu` currently, I am unsure.

I am going to rephrase that question slightly and provide an answer to my rephrased question; let me know if I misunderstood. I am reading this as:

> Should the Drawer with the file-based listing be a component provided via the `oscal-react-library` or should it be defined purely within the example application?

And I think that's a great question! Today, our app menu is fully defined inline in the example app. And the only thing(s) it really imports are the loaders for the different document types. In this case, we would want to define a component that is capable of fetching a list of all document types and displaying that list; and then we'd want to import and use that in `example/src/App.js`. Because it displays something, it will be a React component and because it displays OSCAL things, we'll expose it from our library. And because it's necessary for navigation and creating a minimal app, we'll import and use it in our example application.

**Comment by tuckerzp** [comment]
@kylelaker thank you for the explanation! That is exactly what I was trying to get at. I will look into creating that component.

**Comment by tuckerzp** [comment]
Going off that question a bit more, am I correct in thinking that this component would be imported in `example/src/App.js`? Specifically replacing https://github.com/EasyDynamics/oscal-react-library/blob/develop/example/src/App.js#L162-L197? Or is there another component that would make more sense as a parent?

**Comment by kylelaker** [comment]
That would generally be my assumption here but I don't want to be prescriptive
