### ISSUE TITLE
XSLT 3.0 Processing

### ISSUE THREAD

**Issue by brian-easyd** [EasyDynamics/oscal-react-library#678]
### Description

As an OSCAL tool developer, I require XSLT 3.x processing to run:
- NIST-provided OSCAL format converters
- NIST-provided profile resolution processing
- FedRAMP-provided enhanced validation rules
- (Eventually) Other Schematron- originated  validation rules from other organizations.
- (Eventually) Displaying OSCAL content using organization-provided XSLT to ensure consistent presentation for all stakeholders
- (Eventually) Utilization of XSLT for EDC-provided reporting "skins".

While most modern programming languages natively provide XSLT 1.x processing, enhanced capabilities are required for XSLT 3.x processing.

### Acceptance Criteria

- [ ] Any valid OSCAL profile can be resolved with the NIST-provided profile resolution capability
- [ ] Any valid OSCAL XML file can be converted to JSON with no data loss using the NIST XSLT OSCAL format converters
- [ ] Any FedRAMP XSLT rules file can be processed against any valid OSCAL SSP, AP, AR, or POA&M.

### Proposed Solution

Develop a microservice with an API as in the attached XSLT processing overview.

[XSLT Processing - Overview.pdf](https://github.com/EasyDynamics/oscal-react-library/files/10800005/XSLT.Processing.-.Overview.pdf)

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by brian-easyd** [comment]
Related to #677

**Comment by brian-easyd** [comment]
@brian-easyd to break down into tasks.

**Comment by brian-easyd** [comment]
This was created in the wrong repo. Duplicated to EasyDynamics/easygrc#162 
Closing this one.
