### ISSUE TITLE
Create and Edit Controls 

### ISSUE THREAD

**Issue by brian-comply0** [EasyDynamics/oscal-react-library#924]
### Description

As an OSCAL Catalog Content Author, I want the ability to add new controls to a catalog and edit existing control, so that I can ensure the catalog of controls remains up-to-date.

### Acceptance Criteria

- Ability to add a new control at the top level of the catalog (no group) and directly within any group 
  - Enforce required all fields, such as title.
- Ability to add to and edit the control statement, including sub-statements, statement labels and statement titles.
- Ability to add, alter, and remove parameters

### Additional Notes

See mockups:
Add new control: [https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=918-1989&mode=design&t=vVObf8bT2WzO0l1Y-0](https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=918-1989&mode=design&t=vVObf8bT2WzO0l1Y-0)
Insert parameters: [https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=918-2522&mode=design&t=vVObf8bT2WzO0l1Y-0](https://www.figma.com/file/ntIfIHIhMYbiqS9Nuc7EQG/Catalog-Mockups?type=design&node-id=918-2522&mode=design&t=vVObf8bT2WzO0l1Y-0)

### Implementation

- [ ] I can (or plan to) submit a pull request to implement this
- [ ] Implementing this may result in a breaking change

**Comment by brian-easyd** [comment]
# Button Visibility and Enabled/DIsabled Behavior

## Control Label and Control Title

![image](https://github.com/EasyDynamics/oscal-react-library/assets/106116211/da3db5c0-fc69-4dd3-9aaa-05592a679bf8)

### Button Visibility

- When editing Control Label or Control Title, the cancel (X in circle) and save (check mark in circle) buttons are visible and enabled.
- When editing the Control Title, the Text Formatting buttons are also visible.

|                   | **Text<br>Formatting** | **Save** | **Cancel** |
|-------------------|:-----------------------:|:----------------------:|:------------------:|
| **Control Label** |       Not Visible      |       Visible<br>Enabled       |          Visible<br>Enabled    |
| **Control Title** |       Visible<br>Enabled   |       Visible<br>Enabled       |          Visible<br>Enabled    |

---

## Part Label, Part Title, Part Statement/Prose

![Control Statement Fields (Annotated)](https://github.com/EasyDynamics/oscal-react-library/assets/106116211/818c6061-5a86-4acd-86df-9c2f5ffafde6)

### Button Visibility

- When editing a Part Label, Part Title, Part Statement/Prose, the cancel (X in circle) and save (check mark in circle) buttons are visible and enabled.
- When editing the Control Title, the Text Formatting buttons are also visible.

|                   | **Block<br>Formatting** | **Text<br>Formatting** | **Insert<br>Parameter** | **Show/Hide<br>[Part] Title** | **Insert<br>Part** |
|-------------------|:-----------------------:|:----------------------:|:-----------------------:|:-----------------------------:|:------------------:|
|   **Part Title**  |   Visible<br>Disabled   |   Visible<br>**Enabled**   |   Visible<br>Disabled   |       Visible<br>**Enabled**      | Visible<br>**Enabled** |
|   **Part Label**  |   Visible<br>Disabled   |   Visible<br>Disabled  |   Visible<br>Disabled   |       Visible<br>**Enabled**      | Visible<br>**Enabled** |
|   **Part Prose**  |    Visible<br>**Enabled**   |   Visible<br>**Enabled**   |    Visible<br>**Enabled**   |       Visible<br>**Enabled**      | Visible<br>**Enabled** |

NOTES:

**Comment by brian-easyd** [comment]
# Button Active States

This comment covers:
- Control Label and Control Title
- Part Title, Part Label, and Part Prose (Statement)

## Control Label and Control Title
![Control Label and Title](https://github.com/EasyDynamics/oscal-react-library/assets/106116211/19d456a4-d643-44b2-a6ec-7f787fae3482)

|                   |  **Text<br>Formatting** | **Cancel** | **Save** |
|-------------------|:-----------------------:|:-----------------------------:|:------------------:|
| **Control Label** |       Not Visible       |          Visible<br>Enabled          |     Visible<br>Enabled    |
| **Control Title** |       Visible<br>Enabled       |   Visible<br>Enabled   |     Visible<br>Enabled    |


## Part Title, Part Label and Part Prose (Statement)
![Control Statement Fields (Annotated)](https://github.com/EasyDynamics/oscal-react-library/assets/106116211/346a5564-c296-4416-86e1-13a928cc13a5)


|                   | **Block<br>Formatting** | **Text<br>Formatting** | **Insert<br>Parameter** | **Show/Hide<br>[Part] Title** | **Insert<br>Part** | **Delete<br>Part** |
|-------------------|:-----------------------:|:----------------------:|:-----------------------:|:-----------------------------:|:------------------:|:------------------:|
|   **Part Title**  |   Visible<br>Disabled   |   Visible<br>**Enabled**   |   Visible<br>Disabled   |       Visible<br>**Enabled**      | Visible<br>**Enabled** | Visible<br>_See Notes_ |
|   **Part Label**  |   Visible<br>Disabled   |   Visible<br>Disabled  |   Visible<br>Disabled   |       Visible<br>**Enabled**      | Visible<br>**Enabled** | Visible<br>_See Notes_ |
|   **Part Prose**  |    Visible<br>**Enabled**   |   Visible<br>**Enabled**   |    Visible<br>**Enabled**   |       Visible<br>**Enabled**      | Visible<br>**Enabled** | Visible<br>_See Notes_ |

NOTES:
- Increase/Decrease Indent Button Behavior follows: [https://github.com/EasyDynamics/oscal-react-library/wiki/Specification-%E2%80%90-Indent-States-and-Behaviors](https://github.com/EasyDynamics/oscal-react-library/wiki/Specification-%E2%80%90-Indent-States-and-Behaviors)
- Delete button is always visible when editing a part
  - When editing a new part that has not yet been saved, delete button is disabled
  - When editing a part that was previously saved, delete button is enabled

**Comment by Bronstrom** [comment]
9/7/23 Sprint Planning - Moved from Sprint 54 to Sprint 55

**Comment by Bronstrom** [comment]
9/21/23 Sprint Planning - Moved from Sprint 55 to Sprint 56

**Comment by Bronstrom** [comment]
10/05/23 Sprint Planning - Moved from Sprint 56 to Sprint 57

**Comment by brian-easyd** [comment]
10/19/23 Progress on controls. moving to next sprint.

**Comment by brian-easyd** [comment]
11/9/23 - Some cleanup work pending:
- latency issue
- inactive editing area at bottom

Moving to sprint 59.

**Comment by emcathow** [comment]
11/9/23 - Show/hide title toggle styling update: 


![Image](https://github.com/EasyDynamics/oscal-react-library/assets/128419623/7462aae7-1b7a-4224-9e3f-d4f4ddbb667a)

**Comment by brian-easyd** [comment]
11/29/2023 - moving to sprint 60

**Comment by brian-comply0** [comment]
12/14/2023 
Good progress. Observations include:
- deleting a line in the middle of the statements, causes any newly created statement in that position to unintentionally be placed at the end of the control instead of in the position.
- when moving to a new blank line formatting buttons don't always move
- When adding a title where there is no label or control statement, title doesn't get saved.

**Comment by brian-comply0** [comment]
12/20/2023
Great progress addressing the above. A few additional observations include:
- [ ] keep positioning following a delete is now working as intended except for deleting the first statement.
- [ ] Keep the input boxes visible after any action, even if it means scrolling the list to the input boxes.
- [ ] Very brief flashing animation on added or updated text.

Side note: potential concern for confusion when a statement only has a title, and the user moves to the next blank line for editing. No developer action at time. keep in mind for user testing. @emcathow

**Comment by brian-comply0** [comment]
Moustapha is OOO. Moving to next sprint.

**Comment by brian-comply0** [comment]
2024-01-25 @mpemy intends to demo next week. Blocked by merging of comply0-public to comply0-private
